version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: spring-app
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ~/.m2:/root/.m2  # Кэш для Maven

#  test:
#    build:
#      context: .
#    container_name: spring-test
#
#    env_file:
#      - .env
#    command: mvn --batch-mode test
#
#    depends_on:
#      - postgres
#    environment:
#      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
#    volumes:
#      - ~/.m2:/root/.m2  # Тот же Maven кэш, чтобы не качать зависимости заново

volumes:
  pgdata:
